# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('ansver', models.TextField(verbose_name='Ответ')),
            ],
        ),
    ]
