# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20160914_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True, unique=True),
        ),
    ]
