# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_script_load_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='load_file',
            field=models.FileField(upload_to='script/file'),
        ),
    ]
