# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_script_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField()),
                ('desc_ru', models.TextField(null=True)),
                ('desc_en', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='full_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='full_desc_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='short_desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='short_desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='full_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='full_desc_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='short_desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='short_desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scriptparam',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Script'),
        ),
    ]
