# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20160912_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='category',
        ),
        migrations.AddField(
            model_name='script',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Category'),
        ),
    ]
