# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20160913_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Category'),
        ),
    ]
