# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20160913_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptparam',
            name='default_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptparam',
            name='default_value_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptparam',
            name='default_value_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
