# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20160913_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='script/main'),
        ),
        migrations.AlterField(
            model_name='script',
            name='end',
            field=models.ImageField(blank=True, null=True, upload_to='script/end'),
        ),
        migrations.AlterField(
            model_name='script',
            name='start',
            field=models.ImageField(blank=True, null=True, upload_to='script/start'),
        ),
    ]
