# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20160914_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='image',
        ),
        migrations.AlterField(
            model_name='script',
            name='end',
            field=models.ImageField(upload_to='script/end'),
        ),
        migrations.AlterField(
            model_name='script',
            name='start',
            field=models.ImageField(upload_to='script/start'),
        ),
    ]
