# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20160914_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='shutter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
