# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_script_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='video_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
