# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_use', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='number_en',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='number_ru',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='subject_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='how_to_use.Subject'),
        ),
        migrations.AddField(
            model_name='step',
            name='subject_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='how_to_use.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
