# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_use', '0002_auto_20160922_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='number_en',
        ),
        migrations.RemoveField(
            model_name='step',
            name='number_ru',
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='how_to'),
        ),
    ]
