# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_use', '0003_auto_20160922_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='subject_en',
        ),
        migrations.RemoveField(
            model_name='step',
            name='subject_ru',
        ),
    ]
