# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
